/**
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export interface State {
  id: number;
  name: string;
  counties: string[];
}
export const states: State[] = [
  {
    id: 1,
    name: "Alabama",
    counties: [
      "SAINT CLAIR",
      "JEFFERSON",
      "SHELBY",
      "TALLAPOOSA",
      "BLOUNT",
      "TALLADEGA",
      "MARSHALL",
      "CULLMAN",
      "BIBB",
      "WALKER",
      "CHILTON",
      "COOSA",
      "CLAY",
      "TUSCALOOSA",
      "HALE",
      "PICKENS",
      "GREENE",
      "SUMTER",
      "WINSTON",
      "FAYETTE",
      "MARION",
      "LAMAR",
      "FRANKLIN",
      "MORGAN",
      "LAUDERDALE",
      "LIMESTONE",
      "COLBERT",
      "LAWRENCE",
      "JACKSON",
      "MADISON",
      "ETOWAH",
      "CHEROKEE",
      "DE KALB",
      "AUTAUGA",
      "PIKE",
      "CRENSHAW",
      "MONTGOMERY",
      "BUTLER",
      "BARBOUR",
      "ELMORE",
      "BULLOCK",
      "MACON",
      "LOWNDES",
      "COVINGTON",
      "CALHOUN",
      "CLEBURNE",
      "RANDOLPH",
      "HOUSTON",
      "HENRY",
      "DALE",
      "GENEVA",
      "COFFEE",
      "CONECUH",
      "MONROE",
      "ESCAMBIA",
      "WILCOX",
      "CLARKE",
      "MOBILE",
      "BALDWIN",
      "WASHINGTON",
      "DALLAS",
      "MARENGO",
      "PERRY",
      "LEE",
      "RUSSELL",
      "CHAMBERS",
      "CHOCTAW",
    ],
  },
  {
    id: 2,
    name: "Alaska",
    counties: [
      "ANCHORAGE",
      "BETHEL",
      "ALEUTIANS WEST",
      "LAKE AND PENINSULA",
      "KODIAK ISLAND",
      "ALEUTIANS EAST",
      "WADE HAMPTON",
      "DILLINGHAM",
      "KENAI PENINSULA",
      "YUKON KOYUKUK",
      "VALDEZ CORDOVA",
      "BRISTOL BAY",
      "MATANUSKA SUSITNA",
      "NOME",
      "YAKUTAT",
      "FAIRBANKS NORTH STAR",
      "DENALI",
      "NORTH SLOPE",
      "NORTHWEST ARCTIC",
      "SOUTHEAST FAIRBANKS",
      "JUNEAU",
      "HOONAH ANGOON",
      "HAINES",
      "PETERSBURG",
      "SITKA",
      "SKAGWAY",
      "KETCHIKAN GATEWAY",
      "PRINCE OF WALES HYDER",
      "WRANGELL",
    ],
  },
  { id: 3, name: "American Samoa", counties: ["AMERICAN SAMOA"] },
  {
    id: 4,
    name: "Arizona",
    counties: [
      "MARICOPA",
      "PINAL",
      "GILA",
      "PIMA",
      "YAVAPAI",
      "LA PAZ",
      "YUMA",
      "MOHAVE",
      "GRAHAM",
      "GREENLEE",
      "COCHISE",
      "SANTA CRUZ",
      "NAVAJO",
      "APACHE",
      "COCONINO",
    ],
  },
  {
    id: 5,
    name: "Arkansas",
    counties: [
      "JEFFERSON",
      "DESHA",
      "BRADLEY",
      "ASHLEY",
      "CHICOT",
      "LINCOLN",
      "CLEVELAND",
      "DREW",
      "OUACHITA",
      "CLARK",
      "NEVADA",
      "UNION",
      "DALLAS",
      "COLUMBIA",
      "CALHOUN",
      "HEMPSTEAD",
      "LITTLE RIVER",
      "SEVIER",
      "LAFAYETTE",
      "HOWARD",
      "MILLER",
      "GARLAND",
      "PIKE",
      "HOT SPRING",
      "POLK",
      "MONTGOMERY",
      "PERRY",
      "SALINE",
      "ARKANSAS",
      "JACKSON",
      "WOODRUFF",
      "LONOKE",
      "WHITE",
      "VAN BUREN",
      "PRAIRIE",
      "MONROE",
      "CONWAY",
      "FAULKNER",
      "CLEBURNE",
      "STONE",
      "PULASKI",
      "GRANT",
      "INDEPENDENCE",
      "CRITTENDEN",
      "MISSISSIPPI",
      "LEE",
      "PHILLIPS",
      "SAINT FRANCIS",
      "CROSS",
      "POINSETT",
      "CRAIGHEAD",
      "LAWRENCE",
      "GREENE",
      "RANDOLPH",
      "CLAY",
      "SHARP",
      "IZARD",
      "FULTON",
      "BAXTER",
      "BOONE",
      "CARROLL",
      "MARION",
      "NEWTON",
      "SEARCY",
      "POPE",
      "WASHINGTON",
      "BENTON",
      "MADISON",
      "FRANKLIN",
      "YELL",
      "LOGAN",
      "JOHNSON",
      "SCOTT",
      "SEBASTIAN",
      "CRAWFORD",
    ],
  },
  {
    id: 6,
    name: "California",
    counties: [
      "LOS ANGELES",
      "ORANGE",
      "VENTURA",
      "SAN BERNARDINO",
      "RIVERSIDE",
      "SAN DIEGO",
      "IMPERIAL",
      "INYO",
      "SANTA BARBARA",
      "TULARE",
      "KINGS",
      "KERN",
      "FRESNO",
      "SAN LUIS OBISPO",
      "MONTEREY",
      "MONO",
      "MADERA",
      "MERCED",
      "MARIPOSA",
      "SAN MATEO",
      "SANTA CLARA",
      "SAN FRANCISCO",
      "SACRAMENTO",
      "ALAMEDA",
      "NAPA",
      "CONTRA COSTA",
      "SOLANO",
      "MARIN",
      "SONOMA",
      "SANTA CRUZ",
      "SAN BENITO",
      "SAN JOAQUIN",
      "CALAVERAS",
      "TUOLUMNE",
      "STANISLAUS",
      "MENDOCINO",
      "LAKE",
      "HUMBOLDT",
      "TRINITY",
      "DEL NORTE",
      "SISKIYOU",
      "AMADOR",
      "PLACER",
      "YOLO",
      "EL DORADO",
      "ALPINE",
      "SUTTER",
      "YUBA",
      "NEVADA",
      "SIERRA",
      "COLUSA",
      "GLENN",
      "BUTTE",
      "PLUMAS",
      "SHASTA",
      "MODOC",
      "LASSEN",
      "TEHAMA",
    ],
  },
  {
    id: 7,
    name: "Colorado",
    counties: [
      "JEFFERSON",
      "ARAPAHOE",
      "ADAMS",
      "BROOMFIELD",
      "BOULDER",
      "ELBERT",
      "DOUGLAS",
      "EL PASO",
      "DENVER",
      "PARK",
      "GILPIN",
      "EAGLE",
      "SUMMIT",
      "ROUTT",
      "LAKE",
      "JACKSON",
      "CLEAR CREEK",
      "GRAND",
      "WELD",
      "LARIMER",
      "MORGAN",
      "WASHINGTON",
      "PHILLIPS",
      "LOGAN",
      "YUMA",
      "SEDGWICK",
      "CHEYENNE",
      "LINCOLN",
      "KIT CARSON",
      "TELLER",
      "PUEBLO",
      "LAS ANIMAS",
      "KIOWA",
      "BACA",
      "OTERO",
      "CROWLEY",
      "BENT",
      "HUERFANO",
      "PROWERS",
      "ALAMOSA",
      "CONEJOS",
      "ARCHULETA",
      "LA PLATA",
      "COSTILLA",
      "RIO GRANDE",
      "MINERAL",
      "SAGUACHE",
      "CHAFFEE",
      "GUNNISON",
      "FREMONT",
      "MONTROSE",
      "HINSDALE",
      "CUSTER",
      "DOLORES",
      "MONTEZUMA",
      "SAN MIGUEL",
      "DELTA",
      "OURAY",
      "SAN JUAN",
      "MESA",
      "GARFIELD",
      "MOFFAT",
      "PITKIN",
      "RIO BLANCO",
    ],
  },
  {
    id: 8,
    name: "Connecticut",
    counties: [
      "HARTFORD",
      "LITCHFIELD",
      "TOLLAND",
      "WINDHAM",
      "NEW LONDON",
      "NEW HAVEN",
      "FAIRFIELD",
      "MIDDLESEX",
    ],
  },
  { id: 9, name: "Delaware", counties: ["NEW CASTLE", "KENT", "SUSSEX"] },
  {
    id: 10,
    name: "Federated States of Micronesia",
    counties: ["FEDERATED STATES OF MICRO"],
  },
  {
    id: 11,
    name: "Florida",
    counties: [
      "CLAY",
      "SAINT JOHNS",
      "PUTNAM",
      "SUWANNEE",
      "NASSAU",
      "LAFAYETTE",
      "COLUMBIA",
      "UNION",
      "BAKER",
      "BRADFORD",
      "HAMILTON",
      "MADISON",
      "DUVAL",
      "LAKE",
      "VOLUSIA",
      "FLAGLER",
      "MARION",
      "SUMTER",
      "LEON",
      "FRANKLIN",
      "LIBERTY",
      "GADSDEN",
      "WAKULLA",
      "JEFFERSON",
      "TAYLOR",
      "BAY",
      "JACKSON",
      "CALHOUN",
      "WALTON",
      "HOLMES",
      "WASHINGTON",
      "GULF",
      "ESCAMBIA",
      "SANTA ROSA",
      "OKALOOSA",
      "ALACHUA",
      "GILCHRIST",
      "LEVY",
      "DIXIE",
      "SEMINOLE",
      "ORANGE",
      "BREVARD",
      "INDIAN RIVER",
      "MONROE",
      "MIAMI-DADE",
      "BROWARD",
      "PALM BEACH",
      "HENDRY",
      "MARTIN",
      "GLADES",
      "HILLSBOROUGH",
      "PASCO",
      "PINELLAS",
      "POLK",
      "HIGHLANDS",
      "HARDEE",
      "OSCEOLA",
      "LEE",
      "CHARLOTTE",
      "COLLIER",
      "MANATEE",
      "SARASOTA",
      "DE SOTO",
      "CITRUS",
      "HERNANDO",
      "SAINT LUCIE",
      "OKEECHOBEE",
    ],
  },
  {
    id: 12,
    name: "Georgia",
    counties: [
      "DEKALB",
      "GWINNETT",
      "FULTON",
      "COBB",
      "BARROW",
      "ROCKDALE",
      "NEWTON",
      "WALTON",
      "FORSYTH",
      "CHEROKEE",
      "BARTOW",
      "POLK",
      "FLOYD",
      "CARROLL",
      "HARALSON",
      "DOUGLAS",
      "PAULDING",
      "GORDON",
      "PICKENS",
      "LAMAR",
      "FAYETTE",
      "PIKE",
      "SPALDING",
      "BUTTS",
      "HEARD",
      "MERIWETHER",
      "COWETA",
      "HENRY",
      "TROUP",
      "CLAYTON",
      "UPSON",
      "EMANUEL",
      "MONTGOMERY",
      "WHEELER",
      "JEFFERSON",
      "EVANS",
      "BULLOCH",
      "TATTNALL",
      "SCREVEN",
      "BURKE",
      "TOOMBS",
      "CANDLER",
      "JENKINS",
      "LAURENS",
      "TREUTLEN",
      "HALL",
      "HABERSHAM",
      "BANKS",
      "UNION",
      "FANNIN",
      "HART",
      "JACKSON",
      "FRANKLIN",
      "GILMER",
      "RABUN",
      "WHITE",
      "LUMPKIN",
      "DAWSON",
      "STEPHENS",
      "TOWNS",
      "CLARKE",
      "OGLETHORPE",
      "OCONEE",
      "MORGAN",
      "ELBERT",
      "MADISON",
      "TALIAFERRO",
      "GREENE",
      "WILKES",
      "MURRAY",
      "WALKER",
      "WHITFIELD",
      "CATOOSA",
      "CHATTOOGA",
      "DADE",
      "COLUMBIA",
      "RICHMOND",
      "MCDUFFIE",
      "WARREN",
      "GLASCOCK",
      "LINCOLN",
      "WILCOX",
      "WILKINSON",
      "MONROE",
      "HOUSTON",
      "TAYLOR",
      "DOOLY",
      "PEACH",
      "CRISP",
      "DODGE",
      "BLECKLEY",
      "TWIGGS",
      "WASHINGTON",
      "PUTNAM",
      "JONES",
      "BALDWIN",
      "PULASKI",
      "TELFAIR",
      "JASPER",
      "MACON",
      "JOHNSON",
      "CRAWFORD",
      "BIBB",
      "MARION",
      "HANCOCK",
      "LIBERTY",
      "CHATHAM",
      "EFFINGHAM",
      "MCINTOSH",
      "BRYAN",
      "LONG",
      "WARE",
      "BACON",
      "COFFEE",
      "APPLING",
      "PIERCE",
      "GLYNN",
      "JEFF DAVIS",
      "CHARLTON",
      "BRANTLEY",
      "WAYNE",
      "CAMDEN",
      "LOWNDES",
      "COOK",
      "BERRIEN",
      "CLINCH",
      "ATKINSON",
      "BROOKS",
      "THOMAS",
      "LANIER",
      "ECHOLS",
      "DOUGHERTY",
      "SUMTER",
      "TURNER",
      "MITCHELL",
      "COLQUITT",
      "TIFT",
      "BEN HILL",
      "IRWIN",
      "LEE",
      "WORTH",
      "TALBOT",
      "HARRIS",
      "CHATTAHOOCHEE",
      "SCHLEY",
      "MUSCOGEE",
      "STEWART",
      "WEBSTER",
      "CALHOUN",
      "DECATUR",
      "EARLY",
      "CLAY",
      "TERRELL",
      "GRADY",
      "RANDOLPH",
      "MILLER",
      "SEMINOLE",
      "QUITMAN",
      "BAKER",
    ],
  },
  { id: 13, name: "Guam", counties: ["GUAM"] },
  { id: 14, name: "Hawaii", counties: ["HONOLULU", "KAUAI", "HAWAII", "MAUI"] },
  {
    id: 15,
    name: "Idaho",
    counties: [
      "BANNOCK",
      "BINGHAM",
      "POWER",
      "BUTTE",
      "CARIBOU",
      "BEAR LAKE",
      "CUSTER",
      "FRANKLIN",
      "LEMHI",
      "ONEIDA",
      "TWIN FALLS",
      "CASSIA",
      "BLAINE",
      "GOODING",
      "CAMAS",
      "LINCOLN",
      "JEROME",
      "MINIDOKA",
      "BONNEVILLE",
      "FREMONT",
      "TETON",
      "CLARK",
      "JEFFERSON",
      "MADISON",
      "NEZ PERCE",
      "CLEARWATER",
      "IDAHO",
      "LEWIS",
      "LATAH",
      "ELMORE",
      "BOISE",
      "OWYHEE",
      "CANYON",
      "WASHINGTON",
      "VALLEY",
      "ADAMS",
      "ADA",
      "GEM",
      "PAYETTE",
      "KOOTENAI",
      "SHOSHONE",
      "BONNER",
      "BOUNDARY",
      "BENEWAH",
    ],
  },
  {
    id: 16,
    name: "Illinois",
    counties: [
      "MCHENRY",
      "LAKE",
      "COOK",
      "DUPAGE",
      "KANE",
      "DEKALB",
      "OGLE",
      "WILL",
      "GRUNDY",
      "LIVINGSTON",
      "LA SALLE",
      "KENDALL",
      "LEE",
      "KANKAKEE",
      "IROQUOIS",
      "FORD",
      "VERMILION",
      "CHAMPAIGN",
      "JO DAVIESS",
      "BOONE",
      "STEPHENSON",
      "CARROLL",
      "WINNEBAGO",
      "WHITESIDE",
      "ROCK ISLAND",
      "MERCER",
      "HENRY",
      "BUREAU",
      "PUTNAM",
      "MARSHALL",
      "KNOX",
      "MCDONOUGH",
      "FULTON",
      "WARREN",
      "HENDERSON",
      "STARK",
      "HANCOCK",
      "PEORIA",
      "SCHUYLER",
      "WOODFORD",
      "MASON",
      "TAZEWELL",
      "MCLEAN",
      "LOGAN",
      "DEWITT",
      "MACON",
      "PIATT",
      "DOUGLAS",
      "COLES",
      "MOULTRIE",
      "EDGAR",
      "SHELBY",
      "MADISON",
      "CALHOUN",
      "MACOUPIN",
      "FAYETTE",
      "MONTGOMERY",
      "GREENE",
      "JERSEY",
      "SAINT CLAIR",
      "CHRISTIAN",
      "BOND",
      "WASHINGTON",
      "CLINTON",
      "RANDOLPH",
      "MONROE",
      "PERRY",
      "ADAMS",
      "PIKE",
      "BROWN",
      "EFFINGHAM",
      "WABASH",
      "CRAWFORD",
      "LAWRENCE",
      "RICHLAND",
      "CLARK",
      "CUMBERLAND",
      "JASPER",
      "CLAY",
      "WAYNE",
      "EDWARDS",
      "SANGAMON",
      "MORGAN",
      "SCOTT",
      "CASS",
      "MENARD",
      "MARION",
      "JEFFERSON",
      "FRANKLIN",
      "HAMILTON",
      "WHITE",
      "WILLIAMSON",
      "GALLATIN",
      "JACKSON",
      "UNION",
      "JOHNSON",
      "MASSAC",
      "ALEXANDER",
      "SALINE",
      "HARDIN",
      "POPE",
      "PULASKI",
    ],
  },
  {
    id: 17,
    name: "Indiana",
    counties: [
      "MADISON",
      "HAMILTON",
      "CLINTON",
      "HANCOCK",
      "TIPTON",
      "BOONE",
      "HENDRICKS",
      "RUSH",
      "PUTNAM",
      "JOHNSON",
      "MARION",
      "SHELBY",
      "MORGAN",
      "FAYETTE",
      "HENRY",
      "PORTER",
      "LAKE",
      "JASPER",
      "LA PORTE",
      "NEWTON",
      "STARKE",
      "MARSHALL",
      "KOSCIUSKO",
      "ELKHART",
      "ST JOSEPH",
      "LAGRANGE",
      "NOBLE",
      "HUNTINGTON",
      "STEUBEN",
      "ALLEN",
      "DE KALB",
      "ADAMS",
      "WELLS",
      "WHITLEY",
      "HOWARD",
      "FULTON",
      "MIAMI",
      "CARROLL",
      "GRANT",
      "CASS",
      "WABASH",
      "PULASKI",
      "DEARBORN",
      "UNION",
      "RIPLEY",
      "FRANKLIN",
      "SWITZERLAND",
      "OHIO",
      "SCOTT",
      "CLARK",
      "HARRISON",
      "WASHINGTON",
      "CRAWFORD",
      "FLOYD",
      "BARTHOLOMEW",
      "JACKSON",
      "JENNINGS",
      "JEFFERSON",
      "DECATUR",
      "DELAWARE",
      "WAYNE",
      "JAY",
      "RANDOLPH",
      "BLACKFORD",
      "MONROE",
      "LAWRENCE",
      "GREENE",
      "OWEN",
      "ORANGE",
      "BROWN",
      "DAVIESS",
      "KNOX",
      "DUBOIS",
      "PERRY",
      "MARTIN",
      "SPENCER",
      "PIKE",
      "WARRICK",
      "POSEY",
      "VANDERBURGH",
      "GIBSON",
      "VIGO",
      "PARKE",
      "VERMILLION",
      "CLAY",
      "SULLIVAN",
      "TIPPECANOE",
      "MONTGOMERY",
      "BENTON",
      "FOUNTAIN",
      "WHITE",
      "WARREN",
    ],
  },
  {
    id: 18,
    name: "Iowa",
    counties: [
      "WARREN",
      "ADAIR",
      "DALLAS",
      "MARSHALL",
      "HARDIN",
      "POLK",
      "WAYNE",
      "STORY",
      "CASS",
      "AUDUBON",
      "GUTHRIE",
      "MAHASKA",
      "JASPER",
      "BOONE",
      "MADISON",
      "HAMILTON",
      "FRANKLIN",
      "MARION",
      "LUCAS",
      "GREENE",
      "CARROLL",
      "DECATUR",
      "WRIGHT",
      "RINGGOLD",
      "KEOKUK",
      "POWESHIEK",
      "UNION",
      "MONROE",
      "TAMA",
      "CLARKE",
      "CERRO GORDO",
      "HANCOCK",
      "WINNEBAGO",
      "MITCHELL",
      "WORTH",
      "FLOYD",
      "KOSSUTH",
      "HOWARD",
      "WEBSTER",
      "BUENA VISTA",
      "EMMET",
      "PALO ALTO",
      "HUMBOLDT",
      "SAC",
      "CALHOUN",
      "POCAHONTAS",
      "BUTLER",
      "CHICKASAW",
      "FAYETTE",
      "BUCHANAN",
      "GRUNDY",
      "BLACK HAWK",
      "BREMER",
      "DELAWARE",
      "TAYLOR",
      "ADAMS",
      "MONTGOMERY",
      "PLYMOUTH",
      "SIOUX",
      "WOODBURY",
      "CHEROKEE",
      "IDA",
      "OBRIEN",
      "MONONA",
      "CLAY",
      "LYON",
      "OSCEOLA",
      "DICKINSON",
      "CRAWFORD",
      "SHELBY",
      "POTTAWATTAMIE",
      "HARRISON",
      "MILLS",
      "PAGE",
      "FREMONT",
      "DUBUQUE",
      "JACKSON",
      "CLINTON",
      "CLAYTON",
      "WINNESHIEK",
      "ALLAMAKEE",
      "WASHINGTON",
      "LINN",
      "IOWA",
      "JONES",
      "BENTON",
      "CEDAR",
      "JOHNSON",
      "WAPELLO",
      "JEFFERSON",
      "VAN BUREN",
      "DAVIS",
      "APPANOOSE",
      "DES MOINES",
      "LEE",
      "HENRY",
      "LOUISA",
      "MUSCATINE",
      "SCOTT",
    ],
  },
  {
    id: 19,
    name: "Kansas",
    counties: [
      "ATCHISON",
      "DOUGLAS",
      "LEAVENWORTH",
      "DONIPHAN",
      "LINN",
      "WYANDOTTE",
      "MIAMI",
      "ANDERSON",
      "JOHNSON",
      "FRANKLIN",
      "JEFFERSON",
      "WABAUNSEE",
      "SHAWNEE",
      "MARSHALL",
      "NEMAHA",
      "POTTAWATOMIE",
      "OSAGE",
      "JACKSON",
      "BROWN",
      "GEARY",
      "RILEY",
      "BOURBON",
      "WILSON",
      "CRAWFORD",
      "CHEROKEE",
      "NEOSHO",
      "ALLEN",
      "COFFEY",
      "WOODSON",
      "LYON",
      "MORRIS",
      "MARION",
      "BUTLER",
      "CHASE",
      "GREENWOOD",
      "CLOUD",
      "REPUBLIC",
      "SMITH",
      "WASHINGTON",
      "JEWELL",
      "SEDGWICK",
      "HARPER",
      "SUMNER",
      "COWLEY",
      "HARVEY",
      "PRATT",
      "CHAUTAUQUA",
      "COMANCHE",
      "KINGMAN",
      "KIOWA",
      "BARBER",
      "MCPHERSON",
      "MONTGOMERY",
      "LABETTE",
      "ELK",
      "SALINE",
      "DICKINSON",
      "LINCOLN",
      "MITCHELL",
      "OTTAWA",
      "RICE",
      "CLAY",
      "OSBORNE",
      "ELLSWORTH",
      "RENO",
      "BARTON",
      "RUSH",
      "NESS",
      "EDWARDS",
      "PAWNEE",
      "STAFFORD",
      "ELLIS",
      "PHILLIPS",
      "NORTON",
      "GRAHAM",
      "RUSSELL",
      "TREGO",
      "ROOKS",
      "DECATUR",
      "THOMAS",
      "RAWLINS",
      "CHEYENNE",
      "SHERMAN",
      "GOVE",
      "SHERIDAN",
      "LOGAN",
      "WALLACE",
      "FORD",
      "CLARK",
      "GRAY",
      "HAMILTON",
      "KEARNY",
      "LANE",
      "MEADE",
      "FINNEY",
      "HODGEMAN",
      "STANTON",
      "SEWARD",
      "WICHITA",
      "HASKELL",
      "SCOTT",
      "GREELEY",
      "GRANT",
      "MORTON",
      "STEVENS",
    ],
  },
  {
    id: 20,
    name: "Kentucky",
    counties: [
      "SHELBY",
      "NELSON",
      "TRIMBLE",
      "HENRY",
      "MARION",
      "OLDHAM",
      "JEFFERSON",
      "WASHINGTON",
      "SPENCER",
      "BULLITT",
      "MEADE",
      "BRECKINRIDGE",
      "GRAYSON",
      "HARDIN",
      "MERCER",
      "NICHOLAS",
      "POWELL",
      "ROWAN",
      "MENIFEE",
      "SCOTT",
      "BATH",
      "ESTILL",
      "MONTGOMERY",
      "JESSAMINE",
      "ANDERSON",
      "WOODFORD",
      "BOURBON",
      "OWEN",
      "MADISON",
      "CLARK",
      "JACKSON",
      "ROCKCASTLE",
      "GARRARD",
      "LINCOLN",
      "BOYLE",
      "FAYETTE",
      "FRANKLIN",
      "WHITLEY",
      "LAUREL",
      "KNOX",
      "HARLAN",
      "LESLIE",
      "BELL",
      "LETCHER",
      "CLAY",
      "PERRY",
      "CAMPBELL",
      "BRACKEN",
      "HARRISON",
      "BOONE",
      "PENDLETON",
      "CARROLL",
      "GRANT",
      "KENTON",
      "MASON",
      "FLEMING",
      "GALLATIN",
      "ROBERTSON",
      "BOYD",
      "GREENUP",
      "LAWRENCE",
      "CARTER",
      "LEWIS",
      "ELLIOTT",
      "MARTIN",
      "JOHNSON",
      "WOLFE",
      "BREATHITT",
      "LEE",
      "OWSLEY",
      "MORGAN",
      "MAGOFFIN",
      "PIKE",
      "FLOYD",
      "KNOTT",
      "MCCRACKEN",
      "CALLOWAY",
      "CARLISLE",
      "BALLARD",
      "MARSHALL",
      "GRAVES",
      "LIVINGSTON",
      "HICKMAN",
      "CRITTENDEN",
      "LYON",
      "FULTON",
      "WARREN",
      "ALLEN",
      "BARREN",
      "METCALFE",
      "MONROE",
      "SIMPSON",
      "EDMONSON",
      "BUTLER",
      "LOGAN",
      "TODD",
      "TRIGG",
      "CHRISTIAN",
      "DAVIESS",
      "OHIO",
      "MUHLENBERG",
      "MCLEAN",
      "HANCOCK",
      "HENDERSON",
      "WEBSTER",
      "HOPKINS",
      "CALDWELL",
      "UNION",
      "PULASKI",
      "CASEY",
      "CLINTON",
      "RUSSELL",
      "MCCREARY",
      "WAYNE",
      "HART",
      "ADAIR",
      "LARUE",
      "CUMBERLAND",
      "TAYLOR",
      "GREEN",
    ],
  },
  {
    id: 21,
    name: "Louisiana",
    counties: [
      "JEFFERSON",
      "SAINT CHARLES",
      "SAINT BERNARD",
      "PLAQUEMINES",
      "ST JOHN THE BAPTIST",
      "SAINT JAMES",
      "ORLEANS",
      "LAFOURCHE",
      "ASSUMPTION",
      "SAINT MARY",
      "TERREBONNE",
      "ASCENSION",
      "TANGIPAHOA",
      "SAINT TAMMANY",
      "WASHINGTON",
      "SAINT HELENA",
      "LIVINGSTON",
      "LAFAYETTE",
      "VERMILION",
      "SAINT LANDRY",
      "IBERIA",
      "EVANGELINE",
      "ACADIA",
      "SAINT MARTIN",
      "JEFFERSON DAVIS",
      "CALCASIEU",
      "CAMERON",
      "BEAUREGARD",
      "ALLEN",
      "VERNON",
      "EAST BATON ROUGE",
      "WEST BATON ROUGE",
      "WEST FELICIANA",
      "POINTE COUPEE",
      "IBERVILLE",
      "EAST FELICIANA",
      "BIENVILLE",
      "NATCHITOCHES",
      "CLAIBORNE",
      "CADDO",
      "BOSSIER",
      "WEBSTER",
      "RED RIVER",
      "DE SOTO",
      "SABINE",
      "OUACHITA",
      "RICHLAND",
      "FRANKLIN",
      "MOREHOUSE",
      "UNION",
      "JACKSON",
      "LINCOLN",
      "MADISON",
      "WEST CARROLL",
      "EAST CARROLL",
      "RAPIDES",
      "CONCORDIA",
      "AVOYELLES",
      "CATAHOULA",
      "LA SALLE",
      "TENSAS",
      "WINN",
      "GRANT",
      "CALDWELL",
    ],
  },
  {
    id: 22,
    name: "Maine",
    counties: [
      "YORK",
      "CUMBERLAND",
      "SAGADAHOC",
      "OXFORD",
      "ANDROSCOGGIN",
      "FRANKLIN",
      "KENNEBEC",
      "LINCOLN",
      "WALDO",
      "PENOBSCOT",
      "PISCATAQUIS",
      "HANCOCK",
      "WASHINGTON",
      "AROOSTOOK",
      "SOMERSET",
      "KNOX",
    ],
  },
  { id: 23, name: "Marshall Islands", counties: ["MARSHALL ISLANDS"] },
  {
    id: 24,
    name: "Maryland",
    counties: [
      "HOWARD",
      "CHARLES",
      "SAINT MARYS",
      "PRINCE GEORGES",
      "CALVERT",
      "ANNE ARUNDEL",
      "MONTGOMERY",
      "HARFORD",
      "BALTIMORE",
      "CARROLL",
      "BALTIMORE CITY",
      "ALLEGANY",
      "GARRETT",
      "TALBOT",
      "QUEEN ANNES",
      "CAROLINE",
      "KENT",
      "DORCHESTER",
      "FREDERICK",
      "WASHINGTON",
      "WICOMICO",
      "WORCESTER",
      "SOMERSET",
      "CECIL",
    ],
  },
  {
    id: 25,
    name: "Massachusetts",
    counties: [
      "HAMPDEN",
      "HAMPSHIRE",
      "WORCESTER",
      "BERKSHIRE",
      "FRANKLIN",
      "MIDDLESEX",
      "ESSEX",
      "PLYMOUTH",
      "NORFOLK",
      "BRISTOL",
      "SUFFOLK",
      "BARNSTABLE",
      "DUKES",
      "NANTUCKET",
    ],
  },
  {
    id: 26,
    name: "Michigan",
    counties: [
      "SAINT CLAIR",
      "LAPEER",
      "MACOMB",
      "OAKLAND",
      "WAYNE",
      "WASHTENAW",
      "MONROE",
      "LIVINGSTON",
      "SANILAC",
      "GENESEE",
      "HURON",
      "SHIAWASSEE",
      "SAGINAW",
      "TUSCOLA",
      "ARENAC",
      "BAY",
      "GLADWIN",
      "GRATIOT",
      "CLARE",
      "MIDLAND",
      "OSCODA",
      "ROSCOMMON",
      "OGEMAW",
      "ALCONA",
      "IOSCO",
      "ISABELLA",
      "INGHAM",
      "CLINTON",
      "IONIA",
      "MONTCALM",
      "EATON",
      "BARRY",
      "KALAMAZOO",
      "ALLEGAN",
      "CALHOUN",
      "VAN BUREN",
      "BERRIEN",
      "BRANCH",
      "SAINT JOSEPH",
      "CASS",
      "JACKSON",
      "LENAWEE",
      "HILLSDALE",
      "KENT",
      "MUSKEGON",
      "LAKE",
      "MECOSTA",
      "NEWAYGO",
      "OTTAWA",
      "MASON",
      "OCEANA",
      "WEXFORD",
      "GRAND TRAVERSE",
      "ANTRIM",
      "MANISTEE",
      "BENZIE",
      "LEELANAU",
      "OSCEOLA",
      "MISSAUKEE",
      "KALKASKA",
      "CHEBOYGAN",
      "EMMET",
      "ALPENA",
      "MONTMORENCY",
      "CHIPPEWA",
      "CHARLEVOIX",
      "MACKINAC",
      "OTSEGO",
      "CRAWFORD",
      "PRESQUE ISLE",
      "DICKINSON",
      "KEWEENAW",
      "ALGER",
      "DELTA",
      "MARQUETTE",
      "MENOMINEE",
      "SCHOOLCRAFT",
      "LUCE",
      "IRON",
      "HOUGHTON",
      "BARAGA",
      "ONTONAGON",
      "GOGEBIC",
    ],
  },
  {
    id: 27,
    name: "Minnesota",
    counties: [
      "WASHINGTON",
      "CHISAGO",
      "ANOKA",
      "ISANTI",
      "PINE",
      "GOODHUE",
      "DAKOTA",
      "RICE",
      "SCOTT",
      "WABASHA",
      "STEELE",
      "KANABEC",
      "RAMSEY",
      "HENNEPIN",
      "WRIGHT",
      "SIBLEY",
      "SHERBURNE",
      "RENVILLE",
      "MCLEOD",
      "CARVER",
      "MEEKER",
      "STEARNS",
      "MILLE LACS",
      "LAKE",
      "SAINT LOUIS",
      "COOK",
      "CARLTON",
      "ITASCA",
      "AITKIN",
      "CASS",
      "OLMSTED",
      "MOWER",
      "WINONA",
      "HOUSTON",
      "FILLMORE",
      "DODGE",
      "BLUE EARTH",
      "NICOLLET",
      "FREEBORN",
      "FARIBAULT",
      "LE SUEUR",
      "BROWN",
      "WATONWAN",
      "MARTIN",
      "WASECA",
      "REDWOOD",
      "COTTONWOOD",
      "NOBLES",
      "JACKSON",
      "LINCOLN",
      "MURRAY",
      "LYON",
      "ROCK",
      "PIPESTONE",
      "KANDIYOHI",
      "STEVENS",
      "SWIFT",
      "BIG STONE",
      "LAC QUI PARLE",
      "TRAVERSE",
      "YELLOW MEDICINE",
      "CHIPPEWA",
      "GRANT",
      "DOUGLAS",
      "MORRISON",
      "TODD",
      "POPE",
      "OTTER TAIL",
      "BENTON",
      "CROW WING",
      "HUBBARD",
      "WADENA",
      "BECKER",
      "NORMAN",
      "CLAY",
      "MAHNOMEN",
      "POLK",
      "WILKIN",
      "BELTRAMI",
      "CLEARWATER",
      "LAKE OF THE WOODS",
      "KOOCHICHING",
      "ROSEAU",
      "PENNINGTON",
      "MARSHALL",
      "RED LAKE",
      "KITTSON",
    ],
  },
  {
    id: 28,
    name: "Mississippi",
    counties: [
      "LAFAYETTE",
      "TATE",
      "BENTON",
      "PANOLA",
      "QUITMAN",
      "TIPPAH",
      "MARSHALL",
      "COAHOMA",
      "TUNICA",
      "UNION",
      "DESOTO",
      "WASHINGTON",
      "BOLIVAR",
      "SHARKEY",
      "SUNFLOWER",
      "ISSAQUENA",
      "HUMPHREYS",
      "LEE",
      "PONTOTOC",
      "MONROE",
      "TISHOMINGO",
      "PRENTISS",
      "ALCORN",
      "CALHOUN",
      "ITAWAMBA",
      "CHICKASAW",
      "GRENADA",
      "CARROLL",
      "TALLAHATCHIE",
      "YALOBUSHA",
      "HOLMES",
      "MONTGOMERY",
      "LEFLORE",
      "YAZOO",
      "HINDS",
      "RANKIN",
      "SIMPSON",
      "MADISON",
      "LEAKE",
      "NEWTON",
      "COPIAH",
      "ATTALA",
      "JEFFERSON",
      "SCOTT",
      "CLAIBORNE",
      "SMITH",
      "COVINGTON",
      "ADAMS",
      "LAWRENCE",
      "WARREN",
      "LAUDERDALE",
      "WAYNE",
      "KEMPER",
      "CLARKE",
      "JASPER",
      "WINSTON",
      "NOXUBEE",
      "NESHOBA",
      "GREENE",
      "FORREST",
      "JEFFERSON DAVIS",
      "PERRY",
      "PEARL RIVER",
      "MARION",
      "JONES",
      "GEORGE",
      "LAMAR",
      "HARRISON",
      "HANCOCK",
      "JACKSON",
      "STONE",
      "LINCOLN",
      "FRANKLIN",
      "WILKINSON",
      "PIKE",
      "AMITE",
      "WALTHALL",
      "LOWNDES",
      "CHOCTAW",
      "WEBSTER",
      "CLAY",
      "OKTIBBEHA",
    ],
  },
  {
    id: 29,
    name: "Missouri",
    counties: [
      "SAINT LOUIS",
      "JEFFERSON",
      "FRANKLIN",
      "SAINT FRANCOIS",
      "WASHINGTON",
      "GASCONADE",
      "SAINT LOUIS CITY",
      "SAINT CHARLES",
      "PIKE",
      "MONTGOMERY",
      "WARREN",
      "LINCOLN",
      "AUDRAIN",
      "CALLAWAY",
      "MARION",
      "CLARK",
      "MACON",
      "SCOTLAND",
      "SHELBY",
      "LEWIS",
      "RALLS",
      "KNOX",
      "MONROE",
      "ADAIR",
      "SCHUYLER",
      "SULLIVAN",
      "PUTNAM",
      "LINN",
      "IRON",
      "REYNOLDS",
      "SAINTE GENEVIEVE",
      "WAYNE",
      "MADISON",
      "BOLLINGER",
      "CAPE GIRARDEAU",
      "STODDARD",
      "SCOTT",
      "PERRY",
      "MISSISSIPPI",
      "DUNKLIN",
      "PEMISCOT",
      "NEW MADRID",
      "BUTLER",
      "RIPLEY",
      "CARTER",
      "LAFAYETTE",
      "JACKSON",
      "CASS",
      "RAY",
      "PLATTE",
      "JOHNSON",
      "CLAY",
      "BUCHANAN",
      "GENTRY",
      "WORTH",
      "ANDREW",
      "DEKALB",
      "NODAWAY",
      "HARRISON",
      "CLINTON",
      "HOLT",
      "ATCHISON",
      "LIVINGSTON",
      "DAVIESS",
      "CARROLL",
      "CALDWELL",
      "GRUNDY",
      "CHARITON",
      "MERCER",
      "BATES",
      "SAINT CLAIR",
      "HENRY",
      "VERNON",
      "CEDAR",
      "BARTON",
      "JASPER",
      "MCDONALD",
      "NEWTON",
      "LAWRENCE",
      "BARRY",
      "OSAGE",
      "BOONE",
      "MORGAN",
      "MARIES",
      "MILLER",
      "MONITEAU",
      "CAMDEN",
      "COLE",
      "COOPER",
      "HOWARD",
      "RANDOLPH",
      "PETTIS",
      "SALINE",
      "BENTON",
      "PHELPS",
      "SHANNON",
      "DENT",
      "CRAWFORD",
      "TEXAS",
      "PULASKI",
      "LACLEDE",
      "HOWELL",
      "DALLAS",
      "POLK",
      "DADE",
      "GREENE",
      "OREGON",
      "DOUGLAS",
      "OZARK",
      "CHRISTIAN",
      "STONE",
      "TANEY",
      "HICKORY",
      "WEBSTER",
      "WRIGHT",
    ],
  },
  {
    id: 30,
    name: "Montana",
    counties: [
      "STILLWATER",
      "YELLOWSTONE",
      "ROSEBUD",
      "CARBON",
      "TREASURE",
      "SWEET GRASS",
      "BIG HORN",
      "PARK",
      "FERGUS",
      "WHEATLAND",
      "GOLDEN VALLEY",
      "MEAGHER",
      "MUSSELSHELL",
      "GARFIELD",
      "POWDER RIVER",
      "PETROLEUM",
      "ROOSEVELT",
      "SHERIDAN",
      "MCCONE",
      "RICHLAND",
      "DANIELS",
      "VALLEY",
      "DAWSON",
      "PHILLIPS",
      "CUSTER",
      "CARTER",
      "FALLON",
      "PRAIRIE",
      "WIBAUX",
      "CASCADE",
      "LEWIS AND CLARK",
      "GLACIER",
      "PONDERA",
      "TETON",
      "CHOUTEAU",
      "TOOLE",
      "JUDITH BASIN",
      "LIBERTY",
      "HILL",
      "BLAINE",
      "JEFFERSON",
      "BROADWATER",
      "SILVER BOW",
      "MADISON",
      "DEER LODGE",
      "POWELL",
      "GALLATIN",
      "BEAVERHEAD",
      "MISSOULA",
      "MINERAL",
      "LAKE",
      "RAVALLI",
      "SANDERS",
      "GRANITE",
      "FLATHEAD",
      "LINCOLN",
    ],
  },
  {
    id: 31,
    name: "Nebraska",
    counties: [
      "BUTLER",
      "WASHINGTON",
      "SAUNDERS",
      "CUMING",
      "SARPY",
      "DOUGLAS",
      "CASS",
      "BURT",
      "DODGE",
      "DAKOTA",
      "THURSTON",
      "GAGE",
      "THAYER",
      "NEMAHA",
      "SEWARD",
      "YORK",
      "LANCASTER",
      "PAWNEE",
      "OTOE",
      "JOHNSON",
      "SALINE",
      "RICHARDSON",
      "JEFFERSON",
      "FILLMORE",
      "CLAY",
      "PLATTE",
      "BOONE",
      "WHEELER",
      "MERRICK",
      "COLFAX",
      "ANTELOPE",
      "NANCE",
      "POLK",
      "GREELEY",
      "MADISON",
      "DIXON",
      "HOLT",
      "ROCK",
      "CEDAR",
      "KNOX",
      "BOYD",
      "WAYNE",
      "PIERCE",
      "KEYA PAHA",
      "STANTON",
      "HALL",
      "BUFFALO",
      "CUSTER",
      "VALLEY",
      "SHERMAN",
      "HAMILTON",
      "HOWARD",
      "BLAINE",
      "GARFIELD",
      "DAWSON",
      "LOUP",
      "ADAMS",
      "HARLAN",
      "FURNAS",
      "PHELPS",
      "KEARNEY",
      "WEBSTER",
      "FRANKLIN",
      "GOSPER",
      "NUCKOLLS",
      "RED WILLOW",
      "DUNDY",
      "CHASE",
      "HITCHCOCK",
      "FRONTIER",
      "HAYES",
      "LINCOLN",
      "ARTHUR",
      "DEUEL",
      "MORRILL",
      "KEITH",
      "KIMBALL",
      "CHEYENNE",
      "PERKINS",
      "CHERRY",
      "THOMAS",
      "GARDEN",
      "HOOKER",
      "LOGAN",
      "MCPHERSON",
      "BROWN",
      "BOX BUTTE",
      "GRANT",
      "SHERIDAN",
      "DAWES",
      "SCOTTS BLUFF",
      "BANNER",
      "SIOUX",
    ],
  },
  {
    id: 32,
    name: "Nevada",
    counties: [
      "CLARK",
      "LINCOLN",
      "NYE",
      "ESMERALDA",
      "WHITE PINE",
      "LANDER",
      "EUREKA",
      "WASHOE",
      "LYON",
      "HUMBOLDT",
      "CHURCHILL",
      "DOUGLAS",
      "MINERAL",
      "PERSHING",
      "STOREY",
      "CARSON CITY",
      "ELKO",
    ],
  },
  {
    id: 33,
    name: "New Hampshire",
    counties: [
      "HILLSBOROUGH",
      "ROCKINGHAM",
      "MERRIMACK",
      "GRAFTON",
      "BELKNAP",
      "CARROLL",
      "SULLIVAN",
      "CHESHIRE",
      "COOS",
      "STRAFFORD",
    ],
  },
  {
    id: 34,
    name: "New Jersey",
    counties: [
      "MIDDLESEX",
      "HUDSON",
      "ESSEX",
      "MORRIS",
      "BERGEN",
      "PASSAIC",
      "UNION",
      "SOMERSET",
      "SUSSEX",
      "MONMOUTH",
      "WARREN",
      "HUNTERDON",
      "SALEM",
      "CAMDEN",
      "OCEAN",
      "BURLINGTON",
      "GLOUCESTER",
      "ATLANTIC",
      "CAPE MAY",
      "CUMBERLAND",
      "MERCER",
    ],
  },
  {
    id: 35,
    name: "New Mexico",
    counties: [
      "SANDOVAL",
      "VALENCIA",
      "CIBOLA",
      "BERNALILLO",
      "TORRANCE",
      "SANTA FE",
      "SOCORRO",
      "RIO ARRIBA",
      "SAN JUAN",
      "MCKINLEY",
      "TAOS",
      "SAN MIGUEL",
      "LOS ALAMOS",
      "COLFAX",
      "GUADALUPE",
      "MORA",
      "HARDING",
      "CATRON",
      "SIERRA",
      "DONA ANA",
      "HIDALGO",
      "GRANT",
      "LUNA",
      "CURRY",
      "ROOSEVELT",
      "LEA",
      "DE BACA",
      "QUAY",
      "CHAVES",
      "EDDY",
      "LINCOLN",
      "OTERO",
      "UNION",
    ],
  },
  {
    id: 36,
    name: "New York",
    counties: [
      "SUFFOLK",
      "NEW YORK",
      "RICHMOND",
      "BRONX",
      "WESTCHESTER",
      "PUTNAM",
      "ROCKLAND",
      "ORANGE",
      "NASSAU",
      "QUEENS",
      "KINGS",
      "ALBANY",
      "SCHENECTADY",
      "MONTGOMERY",
      "GREENE",
      "COLUMBIA",
      "RENSSELAER",
      "SARATOGA",
      "FULTON",
      "WASHINGTON",
      "SCHOHARIE",
      "OTSEGO",
      "HAMILTON",
      "DELAWARE",
      "ULSTER",
      "DUTCHESS",
      "SULLIVAN",
      "WARREN",
      "ESSEX",
      "CLINTON",
      "FRANKLIN",
      "SAINT LAWRENCE",
      "ONONDAGA",
      "CAYUGA",
      "OSWEGO",
      "MADISON",
      "CORTLAND",
      "TOMPKINS",
      "ONEIDA",
      "SENECA",
      "CHENANGO",
      "WAYNE",
      "LEWIS",
      "HERKIMER",
      "JEFFERSON",
      "TIOGA",
      "BROOME",
      "ERIE",
      "GENESEE",
      "NIAGARA",
      "WYOMING",
      "ALLEGANY",
      "CATTARAUGUS",
      "CHAUTAUQUA",
      "ORLEANS",
      "MONROE",
      "LIVINGSTON",
      "YATES",
      "ONTARIO",
      "STEUBEN",
      "SCHUYLER",
      "CHEMUNG",
    ],
  },
  {
    id: 37,
    name: "North Carolina",
    counties: [
      "DAVIE",
      "SURRY",
      "FORSYTH",
      "YADKIN",
      "ROWAN",
      "STOKES",
      "ROCKINGHAM",
      "ALAMANCE",
      "RANDOLPH",
      "CHATHAM",
      "MONTGOMERY",
      "CASWELL",
      "GUILFORD",
      "ORANGE",
      "LEE",
      "DAVIDSON",
      "MOORE",
      "PERSON",
      "HARNETT",
      "WAKE",
      "DURHAM",
      "JOHNSTON",
      "GRANVILLE",
      "FRANKLIN",
      "WAYNE",
      "VANCE",
      "WARREN",
      "NASH",
      "EDGECOMBE",
      "BERTIE",
      "BEAUFORT",
      "PITT",
      "WILSON",
      "HERTFORD",
      "NORTHAMPTON",
      "HALIFAX",
      "HYDE",
      "MARTIN",
      "GREENE",
      "PASQUOTANK",
      "DARE",
      "CURRITUCK",
      "PERQUIMANS",
      "CAMDEN",
      "TYRRELL",
      "GATES",
      "WASHINGTON",
      "CHOWAN",
      "STANLY",
      "GASTON",
      "ANSON",
      "IREDELL",
      "CLEVELAND",
      "RUTHERFORD",
      "CABARRUS",
      "MECKLENBURG",
      "LINCOLN",
      "UNION",
      "CUMBERLAND",
      "SAMPSON",
      "ROBESON",
      "BLADEN",
      "DUPLIN",
      "RICHMOND",
      "SCOTLAND",
      "HOKE",
      "NEW HANOVER",
      "BRUNSWICK",
      "PENDER",
      "COLUMBUS",
      "ONSLOW",
      "LENOIR",
      "PAMLICO",
      "CARTERET",
      "CRAVEN",
      "JONES",
      "CATAWBA",
      "AVERY",
      "WATAUGA",
      "WILKES",
      "CALDWELL",
      "BURKE",
      "ASHE",
      "ALLEGHANY",
      "ALEXANDER",
      "BUNCOMBE",
      "SWAIN",
      "MITCHELL",
      "JACKSON",
      "TRANSYLVANIA",
      "HENDERSON",
      "YANCEY",
      "HAYWOOD",
      "POLK",
      "GRAHAM",
      "MACON",
      "MCDOWELL",
      "MADISON",
      "CHEROKEE",
      "CLAY",
    ],
  },
  {
    id: 38,
    name: "North Dakota",
    counties: [
      "RICHLAND",
      "CASS",
      "TRAILL",
      "SARGENT",
      "RANSOM",
      "BARNES",
      "STEELE",
      "GRAND FORKS",
      "WALSH",
      "NELSON",
      "PEMBINA",
      "CAVALIER",
      "RAMSEY",
      "ROLETTE",
      "PIERCE",
      "TOWNER",
      "BOTTINEAU",
      "BENSON",
      "WELLS",
      "EDDY",
      "STUTSMAN",
      "MCINTOSH",
      "LAMOURE",
      "GRIGGS",
      "FOSTER",
      "KIDDER",
      "SHERIDAN",
      "DICKEY",
      "LOGAN",
      "BURLEIGH",
      "MORTON",
      "MERCER",
      "EMMONS",
      "SIOUX",
      "GRANT",
      "OLIVER",
      "MCLEAN",
      "STARK",
      "SLOPE",
      "GOLDEN VALLEY",
      "BOWMAN",
      "DUNN",
      "BILLINGS",
      "MCKENZIE",
      "ADAMS",
      "HETTINGER",
      "WARD",
      "MCHENRY",
      "BURKE",
      "DIVIDE",
      "RENVILLE",
      "WILLIAMS",
      "MOUNTRAIL",
    ],
  },
  {
    id: 39,
    name: "Northern Mariana Islands",
    counties: ["NORTHERN MARIANA ISLANDS"],
  },
  {
    id: 40,
    name: "Ohio",
    counties: [
      "LICKING",
      "FRANKLIN",
      "DELAWARE",
      "KNOX",
      "UNION",
      "CHAMPAIGN",
      "CLARK",
      "FAIRFIELD",
      "MADISON",
      "PERRY",
      "ROSS",
      "PICKAWAY",
      "FAYETTE",
      "HOCKING",
      "MARION",
      "LOGAN",
      "MORROW",
      "WYANDOT",
      "HARDIN",
      "WOOD",
      "SANDUSKY",
      "OTTAWA",
      "LUCAS",
      "ERIE",
      "WILLIAMS",
      "FULTON",
      "HENRY",
      "DEFIANCE",
      "MUSKINGUM",
      "NOBLE",
      "BELMONT",
      "MONROE",
      "GUERNSEY",
      "MORGAN",
      "COSHOCTON",
      "TUSCARAWAS",
      "JEFFERSON",
      "HARRISON",
      "COLUMBIANA",
      "LORAIN",
      "ASHTABULA",
      "CUYAHOGA",
      "GEAUGA",
      "LAKE",
      "SUMMIT",
      "PORTAGE",
      "MEDINA",
      "WAYNE",
      "MAHONING",
      "TRUMBULL",
      "STARK",
      "CARROLL",
      "HOLMES",
      "SENECA",
      "HANCOCK",
      "ASHLAND",
      "HURON",
      "RICHLAND",
      "CRAWFORD",
      "HAMILTON",
      "BUTLER",
      "WARREN",
      "PREBLE",
      "BROWN",
      "CLERMONT",
      "ADAMS",
      "CLINTON",
      "HIGHLAND",
      "GREENE",
      "SHELBY",
      "DARKE",
      "MIAMI",
      "MONTGOMERY",
      "MERCER",
      "PIKE",
      "GALLIA",
      "LAWRENCE",
      "JACKSON",
      "VINTON",
      "SCIOTO",
      "ATHENS",
      "WASHINGTON",
      "MEIGS",
      "ALLEN",
      "PAULDING",
      "PUTNAM",
      "AUGLAIZE",
      "VAN WERT",
    ],
  },
  {
    id: 41,
    name: "Oklahoma",
    counties: [
      "CADDO",
      "GRADY",
      "OKLAHOMA",
      "MCCLAIN",
      "CANADIAN",
      "KINGFISHER",
      "CLEVELAND",
      "WASHITA",
      "LOGAN",
      "MURRAY",
      "BLAINE",
      "KIOWA",
      "GARVIN",
      "STEPHENS",
      "NOBLE",
      "CUSTER",
      "CARTER",
      "LOVE",
      "JOHNSTON",
      "MARSHALL",
      "BRYAN",
      "JEFFERSON",
      "COMANCHE",
      "JACKSON",
      "TILLMAN",
      "COTTON",
      "HARMON",
      "GREER",
      "BECKHAM",
      "ROGER MILLS",
      "DEWEY",
      "GARFIELD",
      "ALFALFA",
      "WOODS",
      "MAJOR",
      "GRANT",
      "WOODWARD",
      "ELLIS",
      "HARPER",
      "BEAVER",
      "TEXAS",
      "CIMARRON",
      "OSAGE",
      "WASHINGTON",
      "TULSA",
      "CREEK",
      "WAGONER",
      "ROGERS",
      "PAWNEE",
      "PAYNE",
      "LINCOLN",
      "NOWATA",
      "CRAIG",
      "MAYES",
      "OTTAWA",
      "DELAWARE",
      "MUSKOGEE",
      "OKMULGEE",
      "PITTSBURG",
      "MCINTOSH",
      "CHEROKEE",
      "SEQUOYAH",
      "HASKELL",
      "ADAIR",
      "PUSHMATAHA",
      "ATOKA",
      "HUGHES",
      "COAL",
      "LATIMER",
      "LE FLORE",
      "KAY",
      "MCCURTAIN",
      "CHOCTAW",
      "POTTAWATOMIE",
      "SEMINOLE",
      "PONTOTOC",
      "OKFUSKEE",
    ],
  },
  {
    id: 42,
    name: "Oregon",
    counties: [
      "WASCO",
      "MARION",
      "CLACKAMAS",
      "WASHINGTON",
      "MULTNOMAH",
      "HOOD RIVER",
      "COLUMBIA",
      "SHERMAN",
      "YAMHILL",
      "CLATSOP",
      "TILLAMOOK",
      "POLK",
      "LINN",
      "BENTON",
      "LINCOLN",
      "LANE",
      "CURRY",
      "COOS",
      "DOUGLAS",
      "JOSEPHINE",
      "JACKSON",
      "KLAMATH",
      "LAKE",
      "DESCHUTES",
      "HARNEY",
      "JEFFERSON",
      "WHEELER",
      "CROOK",
      "UMATILLA",
      "GILLIAM",
      "BAKER",
      "GRANT",
      "MORROW",
      "UNION",
      "WALLOWA",
      "MALHEUR",
    ],
  },
  { id: 43, name: "Palau", counties: ["PALAU"] },
  {
    id: 44,
    name: "Pennsylvania",
    counties: [
      "BEAVER",
      "WASHINGTON",
      "ALLEGHENY",
      "FAYETTE",
      "WESTMORELAND",
      "GREENE",
      "SOMERSET",
      "BEDFORD",
      "FULTON",
      "ARMSTRONG",
      "INDIANA",
      "JEFFERSON",
      "CAMBRIA",
      "CLEARFIELD",
      "ELK",
      "FOREST",
      "CAMERON",
      "BUTLER",
      "CLARION",
      "LAWRENCE",
      "CRAWFORD",
      "MERCER",
      "VENANGO",
      "WARREN",
      "MCKEAN",
      "ERIE",
      "BLAIR",
      "HUNTINGDON",
      "CENTRE",
      "POTTER",
      "CLINTON",
      "TIOGA",
      "BRADFORD",
      "CUMBERLAND",
      "MIFFLIN",
      "LEBANON",
      "DAUPHIN",
      "PERRY",
      "JUNIATA",
      "NORTHUMBERLAND",
      "YORK",
      "LANCASTER",
      "FRANKLIN",
      "ADAMS",
      "LYCOMING",
      "SULLIVAN",
      "UNION",
      "SNYDER",
      "COLUMBIA",
      "MONTOUR",
      "SCHUYLKILL",
      "NORTHAMPTON",
      "LEHIGH",
      "CARBON",
      "BUCKS",
      "MONTGOMERY",
      "BERKS",
      "MONROE",
      "LUZERNE",
      "PIKE",
      "LACKAWANNA",
      "WAYNE",
      "SUSQUEHANNA",
      "WYOMING",
      "DELAWARE",
      "PHILADELPHIA",
      "CHESTER",
    ],
  },
  {
    id: 45,
    name: "Puerto Rico",
    counties: [
      "ADJUNTAS",
      "AGUADA",
      "AGUADILLA",
      "MARICAO",
      "ANASCO",
      "UTUADO",
      "ARECIBO",
      "BARCELONETA",
      "CABO ROJO",
      "PENUELAS",
      "CAMUY",
      "LARES",
      "SAN GERMAN",
      "SABANA GRANDE",
      "CIALES",
      "DORADO",
      "GUANICA",
      "FLORIDA",
      "GUAYANILLA",
      "HATILLO",
      "HORMIGUEROS",
      "ISABELA",
      "JAYUYA",
      "LAJAS",
      "LAS MARIAS",
      "MANATI",
      "MOCA",
      "RINCON",
      "QUEBRADILLAS",
      "MAYAGUEZ",
      "SAN SEBASTIAN",
      "MOROVIS",
      "VEGA ALTA",
      "VEGA BAJA",
      "YAUCO",
      "AGUAS BUENAS",
      "SALINAS",
      "AIBONITO",
      "MAUNABO",
      "ARROYO",
      "PONCE",
      "NAGUABO",
      "NARANJITO",
      "OROCOVIS",
      "RIO GRANDE",
      "PATILLAS",
      "CAGUAS",
      "CANOVANAS",
      "CEIBA",
      "CAYEY",
      "FAJARDO",
      "CIDRA",
      "HUMACAO",
      "SAN LORENZO",
      "SANTA ISABEL",
      "VIEQUES",
      "VILLALBA",
      "YABUCOA",
      "COAMO",
      "LAS PIEDRAS",
      "LOIZA",
      "LUQUILLO",
      "CULEBRA",
      "JUNCOS",
      "GURABO",
      "COMERIO",
      "COROZAL",
      "GUAYAMA",
      "BARRANQUITAS",
      "JUANA DIAZ",
      "SAN JUAN",
      "GUAYNABO",
      "TOA BAJA",
      "TOA ALTA",
      "BAYAMON",
      "CATANO",
      "TRUJILLO ALTO",
      "CAROLINA",
    ],
  },
  {
    id: 46,
    name: "Rhode Island",
    counties: ["NEWPORT", "PROVIDENCE", "WASHINGTON", "BRISTOL", "KENT"],
  },
  {
    id: 47,
    name: "South Carolina",
    counties: [
      "CLARENDON",
      "RICHLAND",
      "BAMBERG",
      "LEXINGTON",
      "KERSHAW",
      "LEE",
      "CHESTER",
      "FAIRFIELD",
      "ORANGEBURG",
      "CALHOUN",
      "UNION",
      "NEWBERRY",
      "SUMTER",
      "WILLIAMSBURG",
      "LANCASTER",
      "DARLINGTON",
      "COLLETON",
      "CHESTERFIELD",
      "AIKEN",
      "FLORENCE",
      "SALUDA",
      "SPARTANBURG",
      "LAURENS",
      "CHEROKEE",
      "CHARLESTON",
      "BERKELEY",
      "DORCHESTER",
      "GEORGETOWN",
      "HORRY",
      "MARLBORO",
      "MARION",
      "DILLON",
      "GREENVILLE",
      "ABBEVILLE",
      "ANDERSON",
      "PICKENS",
      "OCONEE",
      "GREENWOOD",
      "YORK",
      "ALLENDALE",
      "BARNWELL",
      "MCCORMICK",
      "EDGEFIELD",
      "BEAUFORT",
      "HAMPTON",
      "JASPER",
    ],
  },
  {
    id: 48,
    name: "South Dakota",
    counties: [
      "UNION",
      "BROOKINGS",
      "MINNEHAHA",
      "CLAY",
      "MCCOOK",
      "LINCOLN",
      "TURNER",
      "LAKE",
      "MOODY",
      "HUTCHINSON",
      "YANKTON",
      "KINGSBURY",
      "BON HOMME",
      "CODINGTON",
      "DEUEL",
      "GRANT",
      "CLARK",
      "DAY",
      "HAMLIN",
      "ROBERTS",
      "MARSHALL",
      "DAVISON",
      "HANSON",
      "JERAULD",
      "DOUGLAS",
      "SANBORN",
      "GREGORY",
      "MINER",
      "BEADLE",
      "BRULE",
      "CHARLES MIX",
      "BUFFALO",
      "HYDE",
      "HAND",
      "LYMAN",
      "AURORA",
      "BROWN",
      "WALWORTH",
      "SPINK",
      "EDMUNDS",
      "FAULK",
      "MCPHERSON",
      "POTTER",
      "HUGHES",
      "SULLY",
      "JACKSON",
      "TRIPP",
      "JONES",
      "STANLEY",
      "BENNETT",
      "HAAKON",
      "TODD",
      "MELLETTE",
      "PERKINS",
      "CORSON",
      "ZIEBACH",
      "DEWEY",
      "MEADE",
      "CAMPBELL",
      "HARDING",
      "PENNINGTON",
      "SHANNON",
      "BUTTE",
      "CUSTER",
      "LAWRENCE",
      "FALL RIVER",
    ],
  },
  {
    id: 49,
    name: "Tennessee",
    counties: [
      "ROBERTSON",
      "DAVIDSON",
      "DEKALB",
      "WILLIAMSON",
      "CHEATHAM",
      "CANNON",
      "COFFEE",
      "MARSHALL",
      "BEDFORD",
      "SUMNER",
      "STEWART",
      "HICKMAN",
      "DICKSON",
      "SMITH",
      "RUTHERFORD",
      "MONTGOMERY",
      "HOUSTON",
      "WILSON",
      "TROUSDALE",
      "HUMPHREYS",
      "MACON",
      "PERRY",
      "WARREN",
      "LINCOLN",
      "MAURY",
      "GRUNDY",
      "HAMILTON",
      "MCMINN",
      "FRANKLIN",
      "POLK",
      "BRADLEY",
      "MONROE",
      "RHEA",
      "MEIGS",
      "SEQUATCHIE",
      "MARION",
      "MOORE",
      "BLEDSOE",
      "SHELBY",
      "WASHINGTON",
      "GREENE",
      "SULLIVAN",
      "JOHNSON",
      "HAWKINS",
      "CARTER",
      "UNICOI",
      "BLOUNT",
      "ANDERSON",
      "CLAIBORNE",
      "GRAINGER",
      "COCKE",
      "CAMPBELL",
      "MORGAN",
      "KNOX",
      "CUMBERLAND",
      "JEFFERSON",
      "SCOTT",
      "SEVIER",
      "LOUDON",
      "ROANE",
      "HANCOCK",
      "HAMBLEN",
      "UNION",
      "CROCKETT",
      "TIPTON",
      "DYER",
      "HARDEMAN",
      "FAYETTE",
      "HAYWOOD",
      "LAUDERDALE",
      "LAKE",
      "CARROLL",
      "BENTON",
      "HENRY",
      "WEAKLEY",
      "OBION",
      "GIBSON",
      "MADISON",
      "MCNAIRY",
      "DECATUR",
      "HARDIN",
      "HENDERSON",
      "CHESTER",
      "WAYNE",
      "GILES",
      "LAWRENCE",
      "LEWIS",
      "PUTNAM",
      "FENTRESS",
      "OVERTON",
      "PICKETT",
      "CLAY",
      "WHITE",
      "JACKSON",
      "VAN BUREN",
    ],
  },
  {
    id: 50,
    name: "Texas",
    counties: [
      "TRAVIS",
      "SHERMAN",
      "DALLAS",
      "COLLIN",
      "DENTON",
      "GRAYSON",
      "ROCKWALL",
      "ELLIS",
      "NAVARRO",
      "VAN ZANDT",
      "KAUFMAN",
      "HENDERSON",
      "HUNT",
      "WOOD",
      "LAMAR",
      "RED RIVER",
      "FANNIN",
      "DELTA",
      "HOPKINS",
      "RAINS",
      "CAMP",
      "TITUS",
      "FRANKLIN",
      "BOWIE",
      "CASS",
      "MARION",
      "MORRIS",
      "GREGG",
      "PANOLA",
      "UPSHUR",
      "HARRISON",
      "RUSK",
      "SMITH",
      "CHEROKEE",
      "NACOGDOCHES",
      "ANDERSON",
      "LEON",
      "TRINITY",
      "HOUSTON",
      "FREESTONE",
      "MADISON",
      "ANGELINA",
      "NEWTON",
      "SAN AUGUSTINE",
      "SABINE",
      "JASPER",
      "POLK",
      "SHELBY",
      "TYLER",
      "TARRANT",
      "PARKER",
      "JOHNSON",
      "WISE",
      "HOOD",
      "SOMERVELL",
      "HILL",
      "PALO PINTO",
      "CLAY",
      "MONTAGUE",
      "COOKE",
      "WICHITA",
      "ARCHER",
      "KNOX",
      "WILBARGER",
      "YOUNG",
      "BAYLOR",
      "HASKELL",
      "ERATH",
      "STEPHENS",
      "JACK",
      "SHACKELFORD",
      "BROWN",
      "EASTLAND",
      "HAMILTON",
      "COMANCHE",
      "CALLAHAN",
      "THROCKMORTON",
      "BELL",
      "MILAM",
      "CORYELL",
      "MCLENNAN",
      "WILLIAMSON",
      "LAMPASAS",
      "FALLS",
      "ROBERTSON",
      "BOSQUE",
      "LIMESTONE",
      "MASON",
      "RUNNELS",
      "SAN SABA",
      "MCCULLOCH",
      "COLEMAN",
      "LLANO",
      "CONCHO",
      "MENARD",
      "MILLS",
      "KIMBLE",
      "EDWARDS",
      "TOM GREEN",
      "IRION",
      "REAGAN",
      "COKE",
      "SCHLEICHER",
      "CROCKETT",
      "SUTTON",
      "STERLING",
      "HARRIS",
      "FORT BEND",
      "MONTGOMERY",
      "WALKER",
      "LIBERTY",
      "SAN JACINTO",
      "GRIMES",
      "HARDIN",
      "MATAGORDA",
      "COLORADO",
      "AUSTIN",
      "WHARTON",
      "BRAZORIA",
      "WALLER",
      "WASHINGTON",
      "GALVESTON",
      "CHAMBERS",
      "ORANGE",
      "JEFFERSON",
      "BRAZOS",
      "BURLESON",
      "LEE",
      "VICTORIA",
      "REFUGIO",
      "DE WITT",
      "JACKSON",
      "GOLIAD",
      "LAVACA",
      "CALHOUN",
      "LA SALLE",
      "BEXAR",
      "BANDERA",
      "KENDALL",
      "FRIO",
      "MCMULLEN",
      "ATASCOSA",
      "MEDINA",
      "KERR",
      "LIVE OAK",
      "WEBB",
      "ZAPATA",
      "COMAL",
      "BEE",
      "GUADALUPE",
      "KARNES",
      "WILSON",
      "GONZALES",
      "NUECES",
      "JIM WELLS",
      "SAN PATRICIO",
      "KENEDY",
      "DUVAL",
      "BROOKS",
      "ARANSAS",
      "JIM HOGG",
      "KLEBERG",
      "HIDALGO",
      "CAMERON",
      "STARR",
      "WILLACY",
      "BASTROP",
      "BURNET",
      "BLANCO",
      "HAYS",
      "CALDWELL",
      "GILLESPIE",
      "UVALDE",
      "DIMMIT",
      "ZAVALA",
      "KINNEY",
      "REAL",
      "VAL VERDE",
      "TERRELL",
      "MAVERICK",
      "FAYETTE",
      "OLDHAM",
      "GRAY",
      "WHEELER",
      "LIPSCOMB",
      "HUTCHINSON",
      "PARMER",
      "POTTER",
      "MOORE",
      "HEMPHILL",
      "RANDALL",
      "HARTLEY",
      "ARMSTRONG",
      "HALE",
      "DALLAM",
      "DEAF SMITH",
      "CASTRO",
      "LAMB",
      "OCHILTREE",
      "CARSON",
      "HANSFORD",
      "SWISHER",
      "ROBERTS",
      "COLLINGSWORTH",
      "CHILDRESS",
      "DICKENS",
      "FLOYD",
      "COTTLE",
      "HARDEMAN",
      "DONLEY",
      "FOARD",
      "HALL",
      "MOTLEY",
      "KING",
      "BRISCOE",
      "HOCKLEY",
      "COCHRAN",
      "TERRY",
      "CROSBY",
      "YOAKUM",
      "BAILEY",
      "LUBBOCK",
      "GARZA",
      "DAWSON",
      "GAINES",
      "LYNN",
      "JONES",
      "STONEWALL",
      "NOLAN",
      "TAYLOR",
      "HOWARD",
      "MITCHELL",
      "SCURRY",
      "KENT",
      "FISHER",
      "MIDLAND",
      "MARTIN",
      "ANDREWS",
      "REEVES",
      "WARD",
      "PECOS",
      "CRANE",
      "JEFF DAVIS",
      "BORDEN",
      "GLASSCOCK",
      "ECTOR",
      "WINKLER",
      "UPTON",
      "LOVING",
      "EL PASO",
      "BREWSTER",
      "HUDSPETH",
      "PRESIDIO",
      "CULBERSON",
    ],
  },
  { id: 51, name: "US Armed Forces Europe", counties: [] },
  { id: 52, name: "US Armed Forces Pacific", counties: [] },
  {
    id: 53,
    name: "Utah",
    counties: [
      "DUCHESNE",
      "UTAH",
      "SALT LAKE",
      "UINTAH",
      "DAVIS",
      "SUMMIT",
      "MORGAN",
      "TOOELE",
      "DAGGETT",
      "RICH",
      "WASATCH",
      "WEBER",
      "BOX ELDER",
      "CACHE",
      "CARBON",
      "SAN JUAN",
      "EMERY",
      "GRAND",
      "SEVIER",
      "SANPETE",
      "MILLARD",
      "JUAB",
      "KANE",
      "GARFIELD",
      "BEAVER",
      "IRON",
      "WAYNE",
      "WASHINGTON",
      "PIUTE",
    ],
  },
  {
    id: 54,
    name: "Vermont",
    counties: [
      "WINDSOR",
      "ORANGE",
      "CALEDONIA",
      "WINDHAM",
      "BENNINGTON",
      "CHITTENDEN",
      "GRAND ISLE",
      "FRANKLIN",
      "LAMOILLE",
      "ADDISON",
      "WASHINGTON",
      "RUTLAND",
      "ORLEANS",
      "ESSEX",
    ],
  },
  {
    id: 55,
    name: "Virgin Islands",
    counties: ["SAINT THOMAS", "SAINT CROIX", "SAINT JOHN"],
  },
  {
    id: 56,
    name: "Virginia",
    counties: [
      "LOUDOUN",
      "CULPEPER",
      "MANASSAS CITY",
      "PRINCE WILLIAM",
      "MANASSAS PARK CITY",
      "FAUQUIER",
      "FAIRFAX",
      "CLARKE",
      "FAIRFAX CITY",
      "FALLS CHURCH CITY",
      "STAFFORD",
      "ARLINGTON",
      "ALEXANDRIA CITY",
      "FREDERICKSBURG CITY",
      "SPOTSYLVANIA",
      "CAROLINE",
      "NORTHUMBERLAND",
      "ORANGE",
      "ESSEX",
      "WESTMORELAND",
      "KING GEORGE",
      "RICHMOND",
      "LANCASTER",
      "WINCHESTER CITY",
      "FREDERICK",
      "WARREN",
      "RAPPAHANNOCK",
      "SHENANDOAH",
      "PAGE",
      "MADISON",
      "HARRISONBURG CITY",
      "ROCKINGHAM",
      "AUGUSTA",
      "ALBEMARLE",
      "CHARLOTTESVILLE CITY",
      "NELSON",
      "GREENE",
      "FLUVANNA",
      "WAYNESBORO CITY",
      "GLOUCESTER",
      "AMELIA",
      "BUCKINGHAM",
      "HANOVER",
      "KING WILLIAM",
      "NEW KENT",
      "GOOCHLAND",
      "MATHEWS",
      "KING AND QUEEN",
      "LOUISA",
      "CUMBERLAND",
      "CHARLES CITY",
      "MIDDLESEX",
      "HENRICO",
      "JAMES CITY",
      "YORK",
      "CHESTERFIELD",
      "POWHATAN",
      "RICHMOND CITY",
      "WILLIAMSBURG CITY",
      "ACCOMACK",
      "ISLE OF WIGHT",
      "NORTHAMPTON",
      "CHESAPEAKE CITY",
      "SUFFOLK CITY",
      "VIRGINIA BEACH CITY",
      "NORFOLK CITY",
      "NEWPORT NEWS CITY",
      "HAMPTON CITY",
      "POQUOSON CITY",
      "PORTSMOUTH CITY",
      "PRINCE GEORGE",
      "PETERSBURG CITY",
      "BRUNSWICK",
      "DINWIDDIE",
      "NOTTOWAY",
      "SOUTHAMPTON",
      "COLONIAL HEIGHTS CITY",
      "SURRY",
      "GREENSVILLE",
      "FRANKLIN CITY",
      "HOPEWELL CITY",
      "SUSSEX",
      "PRINCE EDWARD",
      "MECKLENBURG",
      "CHARLOTTE",
      "LUNENBURG",
      "APPOMATTOX",
      "ROANOKE CITY",
      "ROANOKE",
      "BOTETOURT",
      "PATRICK",
      "HENRY",
      "PULASKI",
      "MONTGOMERY",
      "FRANKLIN",
      "PITTSYLVANIA",
      "FLOYD",
      "GILES",
      "BEDFORD",
      "MARTINSVILLE CITY",
      "CRAIG",
      "RADFORD",
      "SALEM",
      "BRISTOL CITY",
      "WASHINGTON",
      "WISE",
      "DICKENSON",
      "LEE",
      "RUSSELL",
      "BUCHANAN",
      "SCOTT",
      "NORTON CITY",
      "GRAYSON",
      "SMYTH",
      "WYTHE",
      "BLAND",
      "TAZEWELL",
      "CARROLL",
      "GALAX CITY",
      "STAUNTON CITY",
      "BATH",
      "HIGHLAND",
      "ROCKBRIDGE",
      "BUENA VISTA CITY",
      "ALLEGHANY",
      "COVINGTON CITY",
      "LEXINGTON CITY",
      "LYNCHBURG CITY",
      "CAMPBELL",
      "HALIFAX",
      "AMHERST",
      "DANVILLE CITY",
    ],
  },
  {
    id: 57,
    name: "Washington",
    counties: [
      "KING",
      "SNOHOMISH",
      "KITSAP",
      "KITTITAS",
      "WHATCOM",
      "SKAGIT",
      "SAN JUAN",
      "ISLAND",
      "PIERCE",
      "CLALLAM",
      "JEFFERSON",
      "LEWIS",
      "THURSTON",
      "GRAYS HARBOR",
      "MASON",
      "PACIFIC",
      "COWLITZ",
      "CLARK",
      "KLICKITAT",
      "SKAMANIA",
      "WAHKIAKUM",
      "CHELAN",
      "DOUGLAS",
      "OKANOGAN",
      "GRANT",
      "YAKIMA",
      "SPOKANE",
      "LINCOLN",
      "STEVENS",
      "WHITMAN",
      "ADAMS",
      "FERRY",
      "PEND OREILLE",
      "FRANKLIN",
      "BENTON",
      "WALLA WALLA",
      "COLUMBIA",
      "GARFIELD",
      "ASOTIN",
    ],
  },
  { id: 58, name: "Washington, D.C.", counties: ["DISTRICT OF COLUMBIA"] },
  {
    id: 59,
    name: "West Virginia",
    counties: [
      "MERCER",
      "WYOMING",
      "MCDOWELL",
      "MINGO",
      "GREENBRIER",
      "MONROE",
      "POCAHONTAS",
      "SUMMERS",
      "FAYETTE",
      "KANAWHA",
      "ROANE",
      "RALEIGH",
      "BOONE",
      "PUTNAM",
      "CLAY",
      "LOGAN",
      "NICHOLAS",
      "MASON",
      "JACKSON",
      "CALHOUN",
      "GILMER",
      "BERKELEY",
      "JEFFERSON",
      "MORGAN",
      "HAMPSHIRE",
      "LINCOLN",
      "CABELL",
      "WAYNE",
      "OHIO",
      "BROOKE",
      "MARSHALL",
      "HANCOCK",
      "WOOD",
      "PLEASANTS",
      "WIRT",
      "TYLER",
      "RITCHIE",
      "WETZEL",
      "UPSHUR",
      "WEBSTER",
      "RANDOLPH",
      "BARBOUR",
      "TUCKER",
      "HARRISON",
      "LEWIS",
      "BRAXTON",
      "DODDRIDGE",
      "TAYLOR",
      "PRESTON",
      "MONONGALIA",
      "MARION",
      "GRANT",
      "MINERAL",
      "HARDY",
      "PENDLETON",
    ],
  },
  {
    id: 60,
    name: "Wisconsin",
    counties: [
      "SHEBOYGAN",
      "WASHINGTON",
      "DODGE",
      "OZAUKEE",
      "WAUKESHA",
      "FOND DU LAC",
      "CALUMET",
      "MANITOWOC",
      "JEFFERSON",
      "KENOSHA",
      "RACINE",
      "MILWAUKEE",
      "WALWORTH",
      "ROCK",
      "GREEN",
      "IOWA",
      "LAFAYETTE",
      "DANE",
      "GRANT",
      "RICHLAND",
      "COLUMBIA",
      "SAUK",
      "CRAWFORD",
      "ADAMS",
      "MARQUETTE",
      "GREEN LAKE",
      "JUNEAU",
      "POLK",
      "SAINT CROIX",
      "PIERCE",
      "OCONTO",
      "MARINETTE",
      "FOREST",
      "OUTAGAMIE",
      "SHAWANO",
      "BROWN",
      "FLORENCE",
      "MENOMINEE",
      "KEWAUNEE",
      "DOOR",
      "MARATHON",
      "WOOD",
      "CLARK",
      "PORTAGE",
      "LANGLADE",
      "TAYLOR",
      "LINCOLN",
      "PRICE",
      "ONEIDA",
      "VILAS",
      "ASHLAND",
      "IRON",
      "RUSK",
      "LA CROSSE",
      "BUFFALO",
      "JACKSON",
      "TREMPEALEAU",
      "MONROE",
      "VERNON",
      "EAU CLAIRE",
      "PEPIN",
      "CHIPPEWA",
      "DUNN",
      "BARRON",
      "WASHBURN",
      "BAYFIELD",
      "DOUGLAS",
      "SAWYER",
      "BURNETT",
      "WINNEBAGO",
      "WAUPACA",
      "WAUSHARA",
    ],
  },
  {
    id: 61,
    name: "Wyoming",
    counties: [
      "LARAMIE",
      "ALBANY",
      "PARK",
      "PLATTE",
      "GOSHEN",
      "NIOBRARA",
      "CONVERSE",
      "CARBON",
      "FREMONT",
      "SWEETWATER",
      "WASHAKIE",
      "BIG HORN",
      "HOT SPRINGS",
      "NATRONA",
      "JOHNSON",
      "WESTON",
      "CROOK",
      "CAMPBELL",
      "SHERIDAN",
      "SUBLETTE",
      "UINTA",
      "TETON",
      "LINCOLN",
    ],
  },
];
