name: github pages

on:
  push:
    branches:
      - main
  schedule:
    # Weekly on Thursdays at 3pm PST (UTC-08).
    # Note: github runs the cron from the default branch, in our case "dev".
    - cron:  '0 23 * * 4'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Always deploy from the "main" branch.
          ref: main

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
